[package]
name = "dprint-mconf"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
globset = "0.4"
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
dirs = "6.0"
